AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for Oscar winner predictions
Resources:
  facebookNewsBotUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: oscarsNomsUpdateType
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: oscarsNomsUpdateType-ID-index
          KeySchema:
            - AttributeName: oscarsNomsUpdateType
              KeyType: HASH
            - AttributeName: ID
              KeyType: RANGE
          Projection:
              ProjectionType: ALL
          ProvisionedThroughput:
              ReadCapacityUnits: '2'
              WriteCapacityUnits: '1'
      ProvisionedThroughput:
        ReadCapacityUnits: '2'
        WriteCapacityUnits: '1'
